<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=9" >

<title>MSIA 400 - Assignment 3</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<h1>MSIA 400 - Assignment 3</h1>

<h2><em>Steven Lin</em></h2>

<h2>Setup</h2>

<pre><code class="r">
# Setup ####

# My PC
main = &quot;C:/Users/Steven/Documents/Academics/3_Graduate School/2014-2015 ~ NU/&quot;

# Aginity main = &#39;\\\\nas1/labuser169&#39;

course = &quot;MSIA_400_Analytics for Competitive Advantage&quot;
datafolder = &quot;Lab/Assignment_03&quot;
setwd(file.path(main, course, datafolder))

opts_knit$set(root.dir = getwd())  # set the working directory for all chunks
</code></pre>

<h2>Problem 1</h2>

<pre><code class="r"># Import data
filename = &quot;markov100.txt&quot;
mydata = read.table(filename, header = F, col.names = paste(&quot;S&quot;, 1:100, sep = &quot;&quot;), 
    row.names = paste(&quot;S&quot;, 1:100, sep = &quot;&quot;))
P = as.matrix(mydata)

# Look at data
names(mydata)
head(mydata)[, 1:6]
nrow(mydata)
# summary(mydata)

n = dim(P)[1]
</code></pre>

<h1>Part a</h1>

<pre><code class="r"># install.packages(&#39;expm&#39;)
library(expm)
</code></pre>

<pre><code>## Warning: package &#39;expm&#39; was built under R version 2.15.3
</code></pre>

<pre><code>## Loading required package: Matrix
## Loading required package: lattice
## 
## Attaching package: &#39;expm&#39;
## 
## The following object(s) are masked from &#39;package:Matrix&#39;:
## 
##     expm
</code></pre>

<pre><code class="r">end = 5
a = rep(0, n)
a[1] = 1
ntrans = 10
dist = a %*% (P %^% ntrans)
dist[end]
</code></pre>

<pre><code>## [1] 0.04509
</code></pre>

<p>Probability of being in State 5 after 10 transitions: <strong>0.0451</strong></p>

<h1>Part b</h1>

<pre><code class="r"># install.packages(&#39;expm&#39;)
library(expm)
end = 10
a = rep(0, n)
a[c(1, 2, 3)] = 1/3
ntrans = 10
dist = a %*% (P %^% ntrans)
dist[end]
</code></pre>

<pre><code>## [1] 0.08269
</code></pre>

<p>Suppose we are at one of States 1,2, and 3 with equal probabilities. The probability of being in State 10 after 10 transitions : <strong>0.0827</strong></p>

<h1>Part c</h1>

<pre><code class="r"># install.packages(&#39;expm&#39;)
library(expm)

end = 1
Q = t(P) - diag(n)
Q[n, ] = rep(1, n)
rhs = rep(0, n)
rhs[n] = 1
Pi = solve(Q) %*% rhs
Pi[end]
</code></pre>

<pre><code>## [1] 0.01257
</code></pre>

<p>Steady state probability of being in State 1: <strong>0.0126</strong></p>

<h1>Part d</h1>

<pre><code class="r"># install.packages(&#39;expm&#39;)
library(expm)


# Mean first passage time m ij is the expected number of transitions
# before we first reach state j, given we are currently in i

# Mean first passage time to state Start B: submatrix of P obtained by
# deleting the row and column corresponding to state Sart m: vector of
# mij, i diff Start, j = start e: vector of 1&#39;s m = e + Bm m = (I-B)^-1e

start = 1
end = 100

B = P[-end, -end]
Q = diag(n - 1) - B
e = rep(1, n - 1)
m = solve(Q) %*% e
m[paste(&quot;S&quot;, start, sep = &quot;&quot;), ]
</code></pre>

<pre><code>##    S1 
## 254.9
</code></pre>

<p>Mean first passage time from State 1 to State 100: <strong>254.9395</strong></p>

<h2>Problem 2</h2>

<pre><code class="r"># Import data
filename = &quot;webtraffic.txt&quot;
mydata = read.table(filename, header = T)
P = as.matrix(mydata)

# Look at data
names(mydata)
head(mydata)[, 1:6]
nrow(mydata)
# summary(mydata)
</code></pre>

<h1>Part a</h1>

<pre><code class="r"># sum columns (traffic from tij column) and store in traffic matrix counts
# total traffic between state i to state j
Traffic = matrix(as.matrix(colSums(P)), ncol = 9, byrow = T)
Traffic
</code></pre>

<pre><code>##       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
##  [1,]    0  447  553    0    0    0    0    0    0
##  [2,]    0   23  230  321    0    0    0    0   63
##  [3,]    0  167   43  520    0    0    0    0   96
##  [4,]    0    0    0   44  158  312  247    0  124
##  [5,]    0    0    0    0   22   52   90  127  218
##  [6,]    0    0    0    0   67   21    0  294   97
##  [7,]    0    0    0    0    0   94    7  185   58
##  [8,]    0    0    0    0  262    0    0   30  344
##  [9,]    0    0    0    0    0    0    0    0    0
</code></pre>

<h1>Part b</h1>

<pre><code class="r">Traffic[9, 1] = 1000  #why 9,1 and not 9,9?

sumRows = rowSums(Traffic)
P = Traffic

for (i in 1:9) {
    P[i, ] = P[i, ]/sumRows[i]
}
colnames(P) = paste(&quot;p&quot;, 1:9, sep = &quot;&quot;)
rownames(P) = paste(&quot;p&quot;, 1:9, sep = &quot;&quot;)

# the one step transition probability matrix
P
</code></pre>

<pre><code>##    p1      p2      p3      p4      p5      p6      p7      p8     p9
## p1  0 0.44700 0.55300 0.00000 0.00000 0.00000 0.00000 0.00000 0.0000
## p2  0 0.03611 0.36107 0.50392 0.00000 0.00000 0.00000 0.00000 0.0989
## p3  0 0.20218 0.05206 0.62954 0.00000 0.00000 0.00000 0.00000 0.1162
## p4  0 0.00000 0.00000 0.04972 0.17853 0.35254 0.27910 0.00000 0.1401
## p5  0 0.00000 0.00000 0.00000 0.04322 0.10216 0.17682 0.24951 0.4283
## p6  0 0.00000 0.00000 0.00000 0.13987 0.04384 0.00000 0.61378 0.2025
## p7  0 0.00000 0.00000 0.00000 0.00000 0.27326 0.02035 0.53779 0.1686
## p8  0 0.00000 0.00000 0.00000 0.41195 0.00000 0.00000 0.04717 0.5409
## p9  1 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.0000
</code></pre>

<h1>Part c</h1>

<pre><code class="r">
library(expm)

n = dim(P)[1]
Q = t(P) - diag(n)
Q[n, ] = rep(1, n)
rhs = rep(0, n)
rhs[n] = 1
Pi = solve(Q) %*% rhs

# steady state probability vector
Pi
</code></pre>

<pre><code>##       [,1]
## p1 0.15833
## p2 0.10085
## p3 0.13078
## p4 0.14012
## p5 0.08059
## p6 0.07584
## p7 0.05446
## p8 0.10070
## p9 0.15833
</code></pre>

<pre><code class="r">
</code></pre>

<h1>Part d</h1>

<pre><code class="r">
avgTimePage = c(0.1, 2, 3, 5, 5, 3, 3, 2, 0)  # add zero time p9
names(avgTimePage) = paste(&quot;p&quot;, 1:9, sep = &quot;&quot;)

# this is like an upperbound, know that the average time spent in system
# has to be lower than this
sum(avgTimePage)
</code></pre>

<pre><code>## [1] 23.1
</code></pre>

<pre><code class="r">
# p i is the fraction of time the process is in state i (in the long-run)
# this means 0.15 of the time, the user is in page 1 the lon-run average
# time per period is time p1 * long-run time prob p1 (steady state
# probability state 1)

avgTimeSite2 = sum(avgTimePage * Pi)
avgTimeSite2
</code></pre>

<pre><code>## [1] 2.306
</code></pre>

<pre><code class="r">
# Assume start state x, expected number of step until the first return is
# 1/p(x)
1/Pi[1, 1]
</code></pre>

<pre><code>##    p1 
## 6.316
</code></pre>

<pre><code class="r">
# Mean first passage time m ij is the expected number of transitions
# before we first reach state j, given we are currently in i

# Mean first passage time to state 9 B: submatrix of P obtained by
# deleting the row and column corresponding to state 9 m: vector of mij, i
# diff 9, j = 9 e: vector of 1&#39;s m = e + Bm m = (I-B)^-1e

start = 1
end = 9

B = P[-end, -end]
Q = diag(n - 1) - B
e = rep(1, n - 1)
m = solve(Q) %*% e
m
</code></pre>

<pre><code>##     [,1]
## p1 5.316
## p2 4.402
## p3 4.247
## p4 3.392
## p5 2.430
## p6 2.749
## p7 2.940
## p8 2.100
</code></pre>

<pre><code class="r">
# ave time p1 * # times in p1 + ave time p2 * # times in p2 / (# times in
# p1 + p2)

# repeat mean first passage time but look at time instead of transitions
# mij = pij * tj + sum(k diff j) pik(tk+mkj) mij = e + Bm, where e= pij *
# tj + sum(k diff j) pik(tk) tj = 0 for state 9 then add ti (othwerwise
# will double count)

start = 1
end = 9

B = P[-end, -end]
Q = diag(n - 1) - B

t = avgTimePage[-end]  # there is no time for state 9
e = P[-end, end] * avgTimePage[end] + B %*% t
m = solve(Q) %*% e
m
</code></pre>

<pre><code>##      [,1]
## p1 14.463
## p2 12.224
## p3 11.657
## p4  7.736
## p5  4.355
## p6  5.450
## p7  5.792
## p8  4.144
</code></pre>

<pre><code class="r">
avgTimeSite = m[paste(&quot;p&quot;, start, sep = &quot;&quot;), ] + t[start]
avgTimeSite
</code></pre>

<pre><code>##    p1 
## 14.56
</code></pre>

<pre><code class="r">
# Average time on stie = Total time on site/visits total time on site =
# page a + page bb average time on page = total time on page
# a/(pageviews-Exits)

# Other option is to sum all visits to page i, and do sum(avg tim page i *
# # visits page i)/sum(vists)

sum(apply(Traffic, 2, sum) * avgTimePage)/sum(Traffic[, 1])
</code></pre>

<pre><code>## [1] 14.56
</code></pre>

<p>The average time a visitor spend on the website: 14.563. This is using the approach of mean passage time. Alternatively, multiplying the average times by the number of visits (total time spent in system) divided by the number of visitors gives the same answer. Using your approach (multiply steady state by average times) the answer is: 2.3057. Note that this number seems to low, since we know most customers visit more than one page and the lowest average time per page is 2 min (without counting page 1). </p>

<h1>Part e</h1>

<pre><code class="r">
# from Page2, 30% of the current outgoing traffic to State 3 would move to
# State 6
Traffic[2, 6] = Traffic[2, 3] * 0.3
Traffic[2, 3] = Traffic[2, 3] - Traffic[2, 6]

# 20% of the current outgoing traffic to State 4 would move to State 7
Traffic[2, 7] = Traffic[2, 4] * 0.2
Traffic[2, 4] = Traffic[2, 4] - Traffic[2, 7]

Traffic
</code></pre>

<pre><code>##       [,1] [,2] [,3]  [,4] [,5] [,6]  [,7] [,8] [,9]
##  [1,]    0  447  553   0.0    0    0   0.0    0    0
##  [2,]    0   23  161 256.8    0   69  64.2    0   63
##  [3,]    0  167   43 520.0    0    0   0.0    0   96
##  [4,]    0    0    0  44.0  158  312 247.0    0  124
##  [5,]    0    0    0   0.0   22   52  90.0  127  218
##  [6,]    0    0    0   0.0   67   21   0.0  294   97
##  [7,]    0    0    0   0.0    0   94   7.0  185   58
##  [8,]    0    0    0   0.0  262    0   0.0   30  344
##  [9,] 1000    0    0   0.0    0    0   0.0    0    0
</code></pre>

<pre><code class="r">
sumRows = rowSums(Traffic)
P = Traffic

for (i in 1:9) {
    P[i, ] = P[i, ]/sumRows[i]
}
colnames(P) = paste(&quot;p&quot;, 1:9, sep = &quot;&quot;)
rownames(P) = paste(&quot;p&quot;, 1:9, sep = &quot;&quot;)

# the one step transition probability matrix
P
</code></pre>

<pre><code>##    p1      p2      p3      p4      p5      p6      p7      p8     p9
## p1  0 0.44700 0.55300 0.00000 0.00000 0.00000 0.00000 0.00000 0.0000
## p2  0 0.03611 0.25275 0.40314 0.00000 0.10832 0.10078 0.00000 0.0989
## p3  0 0.20218 0.05206 0.62954 0.00000 0.00000 0.00000 0.00000 0.1162
## p4  0 0.00000 0.00000 0.04972 0.17853 0.35254 0.27910 0.00000 0.1401
## p5  0 0.00000 0.00000 0.00000 0.04322 0.10216 0.17682 0.24951 0.4283
## p6  0 0.00000 0.00000 0.00000 0.13987 0.04384 0.00000 0.61378 0.2025
## p7  0 0.00000 0.00000 0.00000 0.00000 0.27326 0.02035 0.53779 0.1686
## p8  0 0.00000 0.00000 0.00000 0.41195 0.00000 0.00000 0.04717 0.5409
## p9  1 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.0000
</code></pre>

<pre><code class="r">
library(expm)

n = dim(P)[1]
Q = t(P) - diag(n)
Q[n, ] = rep(1, n)
rhs = rep(0, n)
rhs[n] = 1
Pi2 = solve(Q) %*% rhs

# steady state probability vector
Pi2
</code></pre>

<pre><code>##       [,1]
## p1 0.16163
## p2 0.10034
## p3 0.12104
## p4 0.12276
## p5 0.08165
## p6 0.08251
## p7 0.06003
## p8 0.10841
## p9 0.16163
</code></pre>

<pre><code class="r">
# Decide if the link helped balancing the traffic by comparing the
# variance of Pi and Pi2.
Pi - Pi2
</code></pre>

<pre><code>##          [,1]
## p1 -0.0033003
## p2  0.0005116
## p3  0.0097357
## p4  0.0173631
## p5 -0.0010571
## p6 -0.0066697
## p7 -0.0055673
## p8 -0.0077155
## p9 -0.0033003
</code></pre>

<pre><code class="r">var(Pi)
</code></pre>

<pre><code>##          [,1]
## [1,] 0.001411
</code></pre>

<pre><code class="r">var(Pi2)
</code></pre>

<pre><code>##         [,1]
## [1,] 0.00122
</code></pre>

<pre><code class="r">var(Pi2) &lt; var(Pi)
</code></pre>

<pre><code>##      [,1]
## [1,] TRUE
</code></pre>

<pre><code class="r">
(var(Pi2) - var(Pi))/var(Pi)
</code></pre>

<pre><code>##         [,1]
## [1,] -0.1354
</code></pre>

<pre><code class="r">
</code></pre>

<p>The variance of Pi2 is less than the variance of Pi, so adding the links helped reduced the variance and thus balanace the traffic. More specifically, the variance was reduced by 13.5446 %. </p>

</body>

</html>

